/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
//import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DHAWA
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    Color MouseEnteredColor= new Color(0,0,0);
    Color MouseExitColor=new Color(51,51,51);
    Color labelcolor=new Color(153,153,153);
    DefaultTableModel studentmodel,bookmodel;
    
    public Homepage() {
        initComponents();
        DefaulterList dl=new DefaulterList();
setstudentstotable();
setbookstotable();
countbooks();
countissuedbooks();
countstudent();
countdefaulter();
    }
    public void countdefaulter(){
       long l=System.currentTimeMillis();
    Date date=new Date(l);
//    java.sql.Date date=(java.sql.Date) d;
      try{
        
        Connection con=dbconnection.getConnection();
        PreparedStatement pst=con.prepareStatement("select count(id) from issue_book_detail where status=? and due_date<?");
        pst.setString(1,"pending");
        pst.setDate(2,  date);
        ResultSet rs=pst.executeQuery();
        if(rs.next()){
            label_defaulter.setText(rs.getString("count(id)"));
        }
 
    }
    catch(Exception e){
        
        e.printStackTrace();
    }
    }
    public void countbooks(){
        try{
            Connection con=dbconnection.getConnection();
            Statement cs=con.createStatement();
           ResultSet rs=cs.executeQuery("select count(book_id) from book_detail");
           if(rs.next()){
               label_books.setText(rs.getString("count(book_id)"));
           }
           con.close();
           
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
           
    }
     public void countstudent(){
        try{
            Connection con=dbconnection.getConnection();
            Statement cs=con.createStatement();
           ResultSet rs=cs.executeQuery("select count(rollno) from student_detail");
           if(rs.next()){
               label_students.setText(rs.getString("count(rollno)"));
           }
           con.close();
           
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
           
    }
       public void countissuedbooks(){
        try{
            Connection con=dbconnection.getConnection();
            Statement cs=con.createStatement();
           ResultSet rs=cs.executeQuery("select count(id) from issue_book_detail");
           if(rs.next()){
               label_issuedbooks.setText(rs.getString("count(id)"));
           }
           con.close();
           
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
           
    }
    public void setbookstotable(){
    try{
        Connection con=dbconnection.getConnection();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from book_detail");
        while(rs.next()){
            String bookid=rs.getString("book_id");
            String bookname=rs.getString("book_name");
            String author=rs.getString("author");
            int quantity=rs.getInt("quantity");
            Object [] obj={bookid,bookname,author,quantity};
            bookmodel=(DefaultTableModel) tbl_bookdetail.getModel();
            bookmodel.addRow(obj);
        }
    }
    catch(Exception e){
        e.printStackTrace();
//       
    }
}
public void setstudentstotable(){
    try{
        Connection con=dbconnection.getConnection();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from Student_detail");
        while(rs.next()){
            String rollno=rs.getString("rollno");
            String name=rs.getString("student_name");
            String course=rs.getString("course");
            String branch=rs.getString("Branch");
            int batch=rs.getInt("batch");
            int lib_card=rs.getInt("lib_card");
            Object [] obj={rollno,name,course,branch,batch,lib_card};
            studentmodel=(DefaultTableModel) tbl_student_detail.getModel();
            studentmodel.addRow(obj);
        }
    }
    catch(Exception e){
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        label_logout = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        label_managebooks = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        label_managestudents = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        label_issuebook = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        label_return = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        label_record = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        label_books = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        label_students = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        label_issuedbooks = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        label_defaulter = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_student_detail = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bookdetail = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(235, 62, 19));
        jPanel3.setForeground(new java.awt.Color(218, 69, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(1905, 1000));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("=");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library Management System");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("      Welcome ,Admin");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 20, 20));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 5, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 60));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Home Page");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        label_logout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        label_logout.setForeground(new java.awt.Color(255, 255, 255));
        label_logout.setText("Logout");
        label_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_logoutMouseExited(evt);
            }
        });
        jPanel4.add(label_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 210, 50));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Home Page");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 100));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Features");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Home Page");
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        label_managebooks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        label_managebooks.setForeground(new java.awt.Color(153, 153, 153));
        label_managebooks.setText("Manage Books");
        label_managebooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_managebooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_managebooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_managebooksMouseExited(evt);
            }
        });
        jPanel12.add(label_managebooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, 30));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 50));

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 51, 51));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Home Page");
        jPanel15.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        label_managestudents.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        label_managestudents.setForeground(new java.awt.Color(153, 153, 153));
        label_managestudents.setText("Manage Students");
        label_managestudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_managestudentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_managestudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_managestudentsMouseExited(evt);
            }
        });
        jPanel14.add(label_managestudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 30));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 40));

        jPanel16.setBackground(new java.awt.Color(51, 51, 51));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel16MouseExited(evt);
            }
        });
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 51, 51));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Home Page");
        jPanel17.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        label_issuebook.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        label_issuebook.setForeground(new java.awt.Color(153, 153, 153));
        label_issuebook.setText("Issue Books");
        label_issuebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_issuebookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_issuebookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_issuebookMouseExited(evt);
            }
        });
        jPanel16.add(label_issuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 30));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 40));

        panel.setBackground(new java.awt.Color(51, 51, 51));
        panel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                panelFocusLost(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMouseExited(evt);
            }
        });
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 51, 51));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Home Page");
        jPanel19.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        panel.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        label_return.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        label_return.setForeground(new java.awt.Color(153, 153, 153));
        label_return.setText("Return Books");
        label_return.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                label_returnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                label_returnFocusLost(evt);
            }
        });
        label_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_returnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_returnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_returnMouseExited(evt);
            }
        });
        panel.add(label_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 20));

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 40));

        jPanel20.setBackground(new java.awt.Color(51, 51, 51));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel20MouseExited(evt);
            }
        });
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(255, 51, 51));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Home Page");
        jPanel21.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        label_record.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        label_record.setForeground(new java.awt.Color(153, 153, 153));
        label_record.setText("View Records");
        label_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_recordMouseExited(evt);
            }
        });
        jPanel20.add(label_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 20));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 40));

        jPanel22.setBackground(new java.awt.Color(51, 51, 51));
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel22MouseExited(evt);
            }
        });
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(255, 51, 51));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Home Page");
        jPanel23.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        jLabel28.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setText("View Issued Books");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });
        jPanel22.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, 20));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 40));

        jPanel24.setBackground(new java.awt.Color(51, 51, 51));
        jPanel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel24MouseExited(evt);
            }
        });
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(255, 51, 51));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Home Page");
        jPanel25.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 10, 100, -1));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText("Defaulter List");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });
        jPanel24.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 20));

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 720));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_books.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        label_books.setText("10");
        jPanel27.add(label_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 40, 30));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Books Details");
        jPanel26.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jPanel28.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_students.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        label_students.setText("10");
        jPanel28.add(label_students, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 26, 40, 30));

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 180, 80));

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel31.setText("No. of Students");
        jPanel26.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 140, -1));

        jPanel29.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_issuedbooks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        label_issuedbooks.setText("10");
        jPanel29.add(label_issuedbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, 50));

        jPanel26.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 180, 80));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel32.setText("Issued Books");
        jPanel26.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        jPanel30.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_defaulter.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        label_defaulter.setText("10");
        jPanel30.add(label_defaulter, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 30, 30));

        jPanel26.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 180, 80));

        jLabel33.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel33.setText("Defaulter List");
        jPanel26.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        tbl_student_detail.setAutoCreateRowSorter(true);
        tbl_student_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Branch", "Dept", "Batch", "Card"
            }
        ));
        tbl_student_detail.setToolTipText("");
        tbl_student_detail.setGridColor(new java.awt.Color(255, 0, 51));
        tbl_student_detail.setShowGrid(true);
        jScrollPane2.setViewportView(tbl_student_detail);

        jPanel26.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 710, 200));

        tbl_bookdetail.setAutoCreateRowSorter(true);
        tbl_bookdetail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_bookdetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "BookName", "Author", "quantity"
            }
        ));
        tbl_bookdetail.setToolTipText("");
        tbl_bookdetail.setGridColor(new java.awt.Color(255, 0, 51));
        tbl_bookdetail.setShowGrid(true);
        jScrollPane3.setViewportView(tbl_bookdetail);

        jPanel26.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 720, 210));

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel38.setText("No. of Books");
        jPanel26.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel39.setText("Student Details");
        jPanel26.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        getContentPane().add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 940, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void label_managebooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_managebooksMouseClicked
ManageBooks mb=new ManageBooks();
mb.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_label_managebooksMouseClicked

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
jPanel12.setBackground(MouseEnteredColor);    
label_managebooks.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
       jPanel12.setBackground(MouseExitColor);  
       label_managebooks.setForeground(labelcolor);// TODO add your handling code here:
    }//GEN-LAST:event_jPanel12MouseExited

    private void label_managebooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_managebooksMouseEntered
       jPanel12.setBackground(MouseEnteredColor); 
       label_managebooks.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_label_managebooksMouseEntered

    private void label_managebooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_managebooksMouseExited
        jPanel12.setBackground(MouseExitColor); 
        label_managebooks.setForeground(labelcolor);// TODO add your handling code here:
    }//GEN-LAST:event_label_managebooksMouseExited

    private void label_managestudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_managestudentsMouseEntered
jPanel14.setBackground(MouseEnteredColor);    
label_managestudents.setForeground(Color.white);    // TODO add your handling code here:
    }//GEN-LAST:event_label_managestudentsMouseEntered

    private void label_managestudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_managestudentsMouseExited
        // TODO add your handling code here:
        jPanel14.setBackground(MouseExitColor);    
label_managestudents.setForeground(labelcolor);
    }//GEN-LAST:event_label_managestudentsMouseExited

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
       jPanel14.setBackground(MouseEnteredColor);    
label_managestudents.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
         jPanel14.setBackground(MouseExitColor);    
label_managestudents.setForeground(labelcolor);
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseExited

    private void label_managestudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_managestudentsMouseClicked
ManageStudents page=new ManageStudents();
page.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_label_managestudentsMouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
     ManageStudents page=new ManageStudents();
page.setVisible(true);
this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseClicked

    private void label_issuebookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_issuebookMouseEntered
      jPanel16.setBackground(MouseEnteredColor);    
label_issuebook.setForeground(Color.white);    // TODO add your handling code here:
    }//GEN-LAST:event_label_issuebookMouseEntered

    private void label_issuebookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_issuebookMouseExited
      
           jPanel16.setBackground(MouseExitColor);    
label_issuebook.setForeground(labelcolor);// TODO add your handling code here:
    }//GEN-LAST:event_label_issuebookMouseExited

    private void label_issuebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_issuebookMouseClicked
IssueBook page=new IssueBook();  
page.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_label_issuebookMouseClicked

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
    IssueBook page=new IssueBook();  
page.setVisible(true);
this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseClicked

    private void jPanel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseEntered
      jPanel16.setBackground(MouseEnteredColor);    
label_issuebook.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseEntered

    private void jPanel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseExited
      jPanel16.setBackground(MouseExitColor);
label_issuebook.setForeground(labelcolor);//  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseExited

    private void label_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_logoutMouseClicked
Login page=new Login();
page.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_label_logoutMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
     Login page=new Login();
page.setVisible(true);
        this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    Color logouttemp=new Color(51,102,255);
    private void label_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_logoutMouseEntered
       jPanel4.setBackground(MouseEnteredColor);    
label_logout.setForeground(Color.white);     // TODO add your handling code here:
    }//GEN-LAST:event_label_logoutMouseEntered

    private void label_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_logoutMouseExited
        jPanel4.setBackground(logouttemp);
//label_logout.setForeground(labelcolor);// TODO add your handling code here:
    }//GEN-LAST:event_label_logoutMouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
         jPanel4.setBackground(MouseEnteredColor);    
         label_logout.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
       jPanel4.setBackground(logouttemp);
//label_logout.setForeground(labelcolor); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void label_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_returnMouseClicked
ReturnBook page=new ReturnBook();
page.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_label_returnMouseClicked

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
       ReturnBook page=new ReturnBook();
    page.setVisible(true);
    this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_panelMouseClicked

    private void panelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelFocusGained
    // TODO add your handling code here:
    }//GEN-LAST:event_panelFocusGained

    private void panelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelFocusLost
    // TODO add your handling code here:
    }//GEN-LAST:event_panelFocusLost

    private void label_returnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label_returnFocusGained
            // TODO add your handling code here:
    }//GEN-LAST:event_label_returnFocusGained

    private void label_returnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label_returnFocusLost
          // TODO add your handling code here:
    }//GEN-LAST:event_label_returnFocusLost

    private void label_returnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_returnMouseEntered
        panel.setBackground(MouseEnteredColor);    
         label_return.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_label_returnMouseEntered

    private void label_returnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_returnMouseExited
     panel.setBackground(MouseExitColor);    
         label_return.setForeground(labelcolor); // TODO add your handling code here:
    }//GEN-LAST:event_label_returnMouseExited

    private void panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseEntered
        panel.setBackground(MouseEnteredColor);    
         label_return.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_panelMouseEntered

    private void panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseExited
         panel.setBackground(MouseExitColor);    
         label_return.setForeground(labelcolor);// TODO add your handling code here:
    }//GEN-LAST:event_panelMouseExited

    private void label_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_recordMouseEntered
       jPanel20.setBackground(MouseEnteredColor);    
         label_record.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_label_recordMouseEntered

    private void jPanel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseEntered
jPanel20.setBackground(MouseEnteredColor);    
         label_record.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel20MouseEntered

    private void label_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_recordMouseExited
      jPanel20.setBackground(MouseExitColor);
label_record.setForeground(labelcolor);   // TODO add your handling code here:
    }//GEN-LAST:event_label_recordMouseExited

    private void jPanel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseExited
      jPanel20.setBackground(MouseExitColor);
label_record.setForeground(labelcolor);   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel20MouseExited

    private void label_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_recordMouseClicked
ViewRecord page=new ViewRecord();
page.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_label_recordMouseClicked

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
      jPanel22.setBackground(MouseEnteredColor);    
         jLabel28.setForeground(Color.white);     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jPanel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseEntered
         jPanel22.setBackground(MouseEnteredColor);    
         jLabel28.setForeground(Color.white);    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel22MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
       jPanel22.setBackground(MouseExitColor);    
         jLabel28.setForeground(labelcolor); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseExited

    private void jPanel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseExited
      jPanel22.setBackground(MouseExitColor);    
         jLabel28.setForeground(labelcolor);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel22MouseExited

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
IssuedBook page=new IssuedBook();
page.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
   IssuedBook page=new IssuedBook();
page.setVisible(true);
this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jPanel22MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
DefaulterList page=new DefaulterList();
page.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
           jPanel24.setBackground(MouseEnteredColor);    
         jLabel30.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
       jPanel24.setBackground(MouseExitColor);    
         jLabel30.setForeground(labelcolor);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseExited

    private void jPanel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MouseEntered
          jPanel24.setBackground(MouseEnteredColor);    
         jLabel30.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel24MouseEntered

    private void jPanel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MouseExited
      jPanel24.setBackground(MouseExitColor);    
         jLabel30.setForeground(labelcolor);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel24MouseExited

    private void jPanel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MouseClicked
     DefaulterList page=new DefaulterList();
page.setVisible(true);
this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel24MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_books;
    private javax.swing.JLabel label_defaulter;
    private javax.swing.JLabel label_issuebook;
    private javax.swing.JLabel label_issuedbooks;
    private javax.swing.JLabel label_logout;
    private javax.swing.JLabel label_managebooks;
    private javax.swing.JLabel label_managestudents;
    private javax.swing.JLabel label_record;
    private javax.swing.JLabel label_return;
    private javax.swing.JLabel label_students;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbl_bookdetail;
    private javax.swing.JTable tbl_student_detail;
    // End of variables declaration//GEN-END:variables
}
