/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.util.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author DHAWA
 */


public class ManageBooks extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    DefaultTableModel model;
    public ManageBooks() {
        initComponents();
        setbookstotable();
    }
    public boolean checkduplicate(){
        String bookid=field_bookid.getText();
   
        try {
             Connection con=dbconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from book_detail where book_id=?");
            pst.setString(1,bookid);
            int rowcount=pst.executeUpdate();
            if(rowcount>0){
                return true;
            }
            else
            {
                return false;
            }
        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this,"errorfound");
           ex.printStackTrace();
        }
        return false;
    }
public void setbookstotable(){
    try{
        Connection con=dbconnection.getConnection();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from book_detail");
        while(rs.next()){
            String bookid=rs.getString("book_id");
            String bookname=rs.getString("book_name");
            String author=rs.getString("author");
            int quantity=rs.getInt("quantity");
            Object [] obj={bookid,bookname,author,quantity};
            model=(DefaultTableModel) tbl_bookdetail.getModel();
            model.addRow(obj);
        }
    }
    catch(Exception e){
        e.printStackTrace();
//       
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        field_bookid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        field_bookname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        field_author = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        field_quantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bookdetail = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("<- Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 100, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("<- Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Book Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, -1));
        jPanel1.add(field_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Book Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, -1));
        jPanel1.add(field_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Author");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 80, -1));
        jPanel1.add(field_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Quantity");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, -1));
        jPanel1.add(field_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 110, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("  Add Book  ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setText("Update  Book");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Delete Book");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 590));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 50, -1));

        tbl_bookdetail.setAutoCreateRowSorter(true);
        tbl_bookdetail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_bookdetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "BookName", "Author", "quantity"
            }
        ));
        tbl_bookdetail.setToolTipText("");
        tbl_bookdetail.setGridColor(new java.awt.Color(255, 0, 51));
        tbl_bookdetail.setShowGrid(true);
        tbl_bookdetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookdetailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_bookdetail);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 570, 280));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 100, 26));
        jLabel4.setText("Manage Books");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 42, 170, 40));

        jPanel6.setBackground(new java.awt.Color(255, 100, 26));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 640, 590));

        setSize(new java.awt.Dimension(1030, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
Homepage pg=new Homepage();
pg.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_bookdetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookdetailMouseClicked
int rowno=tbl_bookdetail.getSelectedRow();
TableModel model=tbl_bookdetail.getModel();
field_bookid.setText(model.getValueAt(rowno, 0).toString());
field_bookname.setText(model.getValueAt(rowno, 1).toString());
field_author.setText(model.getValueAt(rowno, 2).toString());
field_quantity.setText(model.getValueAt(rowno, 3).toString());
    }//GEN-LAST:event_tbl_bookdetailMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
if(!checkduplicate()){
    String bookid=field_bookid.getText();
    String bookname=field_bookname.getText();
    String author=field_author.getText();
    int quantity=Integer.parseInt(field_quantity.getText());
    try{
        Connection con=dbconnection.getConnection();
        PreparedStatement pst=con.prepareStatement("insert into book_detail(book_id,book_name,author,quantity)  values(?,?,?,?)");
        pst.setString(1, bookid);
        pst.setString(2, bookname);
        pst.setString(3, author);
        pst.setInt(4, quantity);
        int updaterow=pst.executeUpdate();
        if(updaterow>0){
            JOptionPane.showMessageDialog(this,"Book has been inserted");
            if(model!=null){
              model.setRowCount(0);
            setbookstotable();
            }
            else{
                    setbookstotable();
                    }
        }
      
    }
    catch(SQLException e){
        
//            JOptionPane.showMessageDialog(this,"errorfound");
        e.printStackTrace();
    }
    
}
else{
    JOptionPane.showMessageDialog(this,"BOOK ID already Exist");
}
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(checkduplicate()){
    String bookid=field_bookid.getText();
    String bookname=field_bookname.getText();
    String author=field_author.getText();
    int quantity=Integer.parseInt(field_quantity.getText());
    try{
        Connection con=dbconnection.getConnection();
        PreparedStatement pst=con.prepareStatement("update book_detail set  book_name=?,author=?,quantity=? where book_id=?");
       
        pst.setString(1, bookname);
        pst.setString(2, author);
        pst.setInt(3, quantity);
        pst.setString(4, bookid);
        int updaterow=pst.executeUpdate();
        if(updaterow>0){
            JOptionPane.showMessageDialog(this,"Book has been Updated");
              model.setRowCount(0);
            setbookstotable();
        }
      
    }
    catch(SQLException e){
        
//            JOptionPane.showMessageDialog(this,"errorfound");
        e.printStackTrace();
    }
    
}
else{
    JOptionPane.showMessageDialog(this,"BOOK ID NOT FOUND");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
    if(checkduplicate()){
    String bookid=field_bookid.getText();
    try{
        Connection con=dbconnection.getConnection();
        PreparedStatement pst=con.prepareStatement("delete from book_detail where book_id=?");      
        pst.setString(1, bookid);
        int updaterow=pst.executeUpdate();
        if(updaterow>0){
            JOptionPane.showMessageDialog(this,"Book has been Deleted");
              model.setRowCount(0);
            setbookstotable();
        }
      
    }
    catch(SQLException e){
        
//            JOptionPane.showMessageDialog(this,"errorfound");
        e.printStackTrace();
    }
    
}
else{
    JOptionPane.showMessageDialog(this,"BOOK ID NOT FOUND");
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_author;
    private javax.swing.JTextField field_bookid;
    private javax.swing.JTextField field_bookname;
    private javax.swing.JTextField field_quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_bookdetail;
    // End of variables declaration//GEN-END:variables
}

