/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DHAWA
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        label_duedate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        label_issue = new javax.swing.JLabel();
        label_issueid = new javax.swing.JLabel();
        label_bookid = new javax.swing.JLabel();
        label_rollno = new javax.swing.JLabel();
        label_issue_date = new javax.swing.JLabel();
        label_Notfound = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        field_rollno = new javax.swing.JTextField();
        field_bookid = new javax.swing.JTextField();
        button_returnbook = new javax.swing.JButton();
        button_find_detail = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        field_issueid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lib.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 430));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setText("<- Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, 20));

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setText("<- Back");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 680));

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Issued Book Details");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 220, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 250, 5));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Due date   :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, -1));

        label_duedate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_duedate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(label_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 190, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Book id    :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rollno      :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 250, 90, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Issue date :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 30));

        label_issue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_issue.setForeground(new java.awt.Color(255, 255, 255));
        label_issue.setText("Issue Id    :");
        jPanel4.add(label_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 150, 90, -1));

        label_issueid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_issueid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(label_issueid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 190, 30));

        label_bookid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_bookid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(label_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 190, 30));

        label_rollno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_rollno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(label_rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 190, 30));

        label_issue_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_issue_date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(label_issue_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 190, 30));

        label_Notfound.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Notfound.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(label_Notfound, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 180, 30));

        label_status.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_status.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Status        :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 370, 700));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 102, 51));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 50, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Return Book");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, 30));

        jPanel7.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 5));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 102, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel13.setText("X");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 40, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 51));
        jLabel14.setText("Return Book");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, 30));

        jPanel11.setBackground(new java.awt.Color(255, 102, 51));
        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 5));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 370, 660));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 51));
        jLabel15.setText("Roll no     :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 51));
        jLabel16.setText("Book id    :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 30));

        field_rollno.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        field_rollno.setForeground(new java.awt.Color(255, 102, 51));
        jPanel5.add(field_rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 250, 150, -1));

        field_bookid.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        field_bookid.setForeground(new java.awt.Color(255, 102, 51));
        field_bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_bookidActionPerformed(evt);
            }
        });
        jPanel5.add(field_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 190, 150, -1));

        button_returnbook.setBackground(new java.awt.Color(255, 102, 51));
        button_returnbook.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        button_returnbook.setText("Return Book");
        button_returnbook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        button_returnbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_returnbookMouseClicked(evt);
            }
        });
        jPanel5.add(button_returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 130, 40));

        button_find_detail.setBackground(new java.awt.Color(51, 153, 255));
        button_find_detail.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        button_find_detail.setText("Find Details");
        button_find_detail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_find_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_find_detailMouseClicked(evt);
            }
        });
        jPanel5.add(button_find_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 130, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 51));
        jLabel18.setText("Issue id    :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 30));

        field_issueid.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        field_issueid.setForeground(new java.awt.Color(255, 102, 51));
        field_issueid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_issueidActionPerformed(evt);
            }
        });
        jPanel5.add(field_issueid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 370, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String status;
//    int lib_card;
    public boolean checkfield(){
         String bookid=field_bookid.getText();
        String rollno=field_rollno.getText();
        if(!rollno.isEmpty() && !bookid.isEmpty()){
            return true;
        }
        else if(!rollno.isEmpty()){
              label_issueid.setText("");
                label_bookid.setText("");
                label_rollno.setText("");
                label_issue_date.setText("");
                label_duedate.setText("");
                label_status.setText("");
            JOptionPane.showMessageDialog( this,"Enter Book id");
//            return false;
        }
        else{
              label_issueid.setText("");
                label_bookid.setText("");
                label_rollno.setText("");
                label_issue_date.setText("");
                label_duedate.setText("");
                label_status.setText("");
            JOptionPane.showMessageDialog( this,"Enter Rollno");
//            return false;
        }
        return false;
    }
    public void getissuedetail(){
        int id;
        String x=field_issueid.getText();
        if(x.isEmpty()){
            id=0;
        }
        else{
            id=Integer.parseInt(field_issueid.getText());
        }
//        JOptionPane.showMessageDialog(this,id);
        String bookid=field_bookid.getText();
        String rollno=field_rollno.getText();
        if(id==0){ try{
            Connection con=dbconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from issue_book_detail where bookid=? and rollno=? ");
            pst.setString(1,bookid);
            pst.setString(2,rollno);
//          
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                label_issueid.setText((rs.getString("id")));
                label_bookid.setText(rs.getString("bookid"));
                label_rollno.setText(rs.getString("rollno"));
                label_issue_date.setText(rs.getString("issue_date"));
                label_duedate.setText(rs.getString("due_date"));
                label_status.setText(rs.getString("status"));
                status=rs.getString("status");

                label_Notfound.setText("");
            }
            else{
                label_issueid.setText("");
                label_bookid.setText("");
                label_rollno.setText("");
                label_issue_date.setText("");
                label_duedate.setText("");
                label_status.setText("");
                status="returned";
                label_Notfound.setText("No Record found");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
        else{
            try{
            Connection con=dbconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from issue_book_detail where id=?");
            pst.setInt(1,id);

            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                label_issueid.setText((rs.getString("id")));
                label_bookid.setText(rs.getString("bookid"));
                label_rollno.setText(rs.getString("rollno"));
                label_issue_date.setText(rs.getString("issue_date"));
                label_duedate.setText(rs.getString("due_date"));
                label_status.setText(rs.getString("status"));
                status=rs.getString("status");

                label_Notfound.setText("");
            }
            else{
                label_issueid.setText("");
                label_bookid.setText("");
                label_rollno.setText("");
                label_issue_date.setText("");
                label_duedate.setText("");
                label_status.setText("");
                status="returned";
                label_Notfound.setText("No Record found");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        }
    }
    public void setquantity(String bookid, int quantity){
        try{
            Connection con=dbconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("update book_detail set quantity=? where book_id=?");
            pst.setInt(1,quantity);
            pst.setString(2,bookid);
            pst.executeQuery();
            con.close();
        }
        catch(Exception e){
            e.printStackTrace();

        }
    }
    public void getquantity(){
        String book_id=label_bookid.getText();
        int quantity=0;
        
        try{
            Connection con=dbconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select quantity from book_detail where book_id=?");
            pst.setString(1,book_id);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
            quantity=rs.getInt("quantity");
            setquantity(book_id,quantity+1);
        }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void set_libcard(String rollno,int card){
        try{
            Connection con=dbconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("update student_detail set lib_card=? where rollno=?");
            pst.setInt(1,card);
            pst.setString(2,rollno);
            pst.executeQuery();
        }
        catch(Exception e){
            e.printStackTrace();
        } 
    }
    public void get_libcard(){
        String rollno=label_rollno.getText();
         int card=0;
        
//        String rollno=label_rollno.getText();
        try{
            Connection con=dbconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select lib_card from student_detail where rollno=?");
            pst.setString(1,rollno);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
            card=rs.getInt("lib_card");
            if(card<4){
            set_libcard(rollno,card+1);
            }
        }
        }
        catch(Exception e){
            e.printStackTrace();
//            
//JOptionPane.showMessageDialog(this,"error");
        }
    }
   public boolean checkfine(int id){
       try{
           
           Connection con=dbconnection.getConnection();
           PreparedStatement pst=con.prepareStatement("Select fine from issue_book_detail where id=?");
           pst.setInt(1,id);
           ResultSet rs=pst.executeQuery();
           if(rs.next()){
               int fine=rs.getInt("fine");
               if(fine>0){
                int val=   JOptionPane.showConfirmDialog(this, "Click ok if fine is paid fine : "+fine);
                if(val==0 ){
                    
                    return true;
                }
               
                else if(val==1){
                    JOptionPane.showMessageDialog(this,"Fine Not paid ");
                }
                else{
                    
                }
               }
           }
           
       }
       catch(Exception e){
           e.printStackTrace();
       }
       return false;
   }
    public void returndetail(){
     
       String idcheck=label_issueid.getText();
       if(idcheck==""){
                     JOptionPane.showMessageDialog(this,"Enter Details");
       }
       else{
            try{
                  int id=Integer.parseInt(label_issueid.getText());
                   if(checkfine(id)){
               Connection con=dbconnection.getConnection();
               PreparedStatement pst=con.prepareStatement("update issue_book_detail set status=? where id=?");
               pst.setString(1,"Returned");

               pst.setInt(2, id);
               int count=pst.executeUpdate();
              
               if(count>0 && status.equals("pending")){
                   JOptionPane.showMessageDialog(this,"Book Returned");
                   getissuedetail();
               }
               else if(count>0 && status.equals("returned")){
                   JOptionPane.showMessageDialog(this,"Book returned");
               }
               else{
                   JOptionPane.showMessageDialog(this,"Book already returned");
               }
           }
            }
           catch(Exception e){
               e.printStackTrace();

//           JOptionPane.showMessageDialog(this,"Enter Details");
           }
       }
       
    }
    private void field_bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_bookidActionPerformed

    private void button_find_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_find_detailMouseClicked
        if(checkfield()){
        getissuedetail();}
// TODO add your handling code here:
    }//GEN-LAST:event_button_find_detailMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
Homepage page=new Homepage();
page.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       Homepage page=new Homepage();
page.setVisible(true);
this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void button_returnbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnbookMouseClicked
returndetail();   
getquantity();
get_libcard();// TODO add your handling code here:
    }//GEN-LAST:event_button_returnbookMouseClicked

    private void field_issueidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_issueidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_issueidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_find_detail;
    private javax.swing.JButton button_returnbook;
    private javax.swing.JTextField field_bookid;
    private javax.swing.JTextField field_issueid;
    private javax.swing.JTextField field_rollno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label_Notfound;
    private javax.swing.JLabel label_bookid;
    private javax.swing.JLabel label_duedate;
    private javax.swing.JLabel label_issue;
    private javax.swing.JLabel label_issue_date;
    private javax.swing.JLabel label_issueid;
    private javax.swing.JLabel label_rollno;
    private javax.swing.JLabel label_status;
    // End of variables declaration//GEN-END:variables
}
