/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DHAWA
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public signup() {
        initComponents();
    }

    public void insertsignupdetails() {
        String name = txt_username.getText();
        char pwd[] = (txt_Password.getPassword());
        String spwd = "";
        for (int i = 0; i < pwd.length; i++) {
            spwd += pwd[i];
        }
        String email = txt_email.getText();
        String contact = txt_contact.getText();

        try {
            Connection con = dbconnection.getConnection();
            String sql = "insert into userlib (name, password,email,contact) values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, name);
            pst.setString(2, spwd);
            pst.setString(3, email);
            pst.setString(4, contact);
            int updatedRowCount = pst.executeUpdate();
            if (updatedRowCount > 0) {
                JOptionPane.showMessageDialog(this, "Record inserted succesfully");
            } else {
                JOptionPane.showMessageDialog(this, "Record inserted Failure");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean validSignup() {
        String name = txt_username.getText();
        char pwd[] = (txt_Password.getPassword());
        String spwd = "";
        for (int i = 0; i < pwd.length; i++) {
            spwd += pwd[i];
        }
        String email = txt_email.getText();
        String contact = txt_contact.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER NAME");
            return false;
        }
        if (spwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER password");
            return false;
        }
        if (spwd.length() < 8) {
            JOptionPane.showMessageDialog(this, "invalid password\n Short length");

            return false;
        }
        if (email.isEmpty() || !email.contains("@gmail.com")) {
            JOptionPane.showMessageDialog(this, "invalid EMAIL");
            return false;
        }
        if (contact.length() != 10 || contact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "invalid Contact");

            return false;

        }
        return true;
    }

    public boolean checkduplicate() {
        String name = txt_username.getText();
        boolean isexist = false;
        try {
            Connection con = dbconnection.getConnection();
            PreparedStatement pst = con.prepareStatement("Select * from userlib where name=?");
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                isexist = true;
            } else {
                isexist = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isexist;

    }
//    System.out.println(name+pwd+email+contact);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_welcome = new javax.swing.JLabel();
        label_agc = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        label_contact = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        button_signup = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 214, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_welcome.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        label_welcome.setText("WELCOME TO LIBRARY MANAGEMENT SYSTEM");
        jPanel1.add(label_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 458, 60));

        label_agc.setFont(new java.awt.Font("Gabriola", 3, 36)); // NOI18N
        label_agc.setText(" Amritsar Group Of Colleges");
        jPanel1.add(label_agc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 410, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/R.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 720, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 680));

        jPanel2.setBackground(new java.awt.Color(255, 105, 2));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LIBRARY MANAGEMENT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 169, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 25));

        txt_username.setBorder(null);
        txt_username.setOpaque(true);
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 127, -1));

        label_username.setFont(new java.awt.Font("Nirmala UI", 2, 14)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setText("USERNAME");
        jPanel2.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 127, -1));

        label_password.setForeground(new java.awt.Color(255, 255, 255));
        label_password.setText("PASSWORD");
        jPanel2.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 71, -1));

        label_email.setForeground(new java.awt.Color(255, 255, 255));
        label_email.setText("EMAIL");
        jPanel2.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 37, -1));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 127, -1));

        label_contact.setForeground(new java.awt.Color(255, 255, 255));
        label_contact.setText("CONTACT");
        jPanel2.add(label_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 64, -1));
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 127, -1));

        button_signup.setBackground(new java.awt.Color(255, 153, 153));
        button_signup.setText("SIGN UP");
        button_signup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        button_signup.setOpaque(true);
        button_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_signupMouseClicked(evt);
            }
        });
        button_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signupActionPerformed(evt);
            }
        });
        jPanel2.add(button_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 80, 20));

        jLabel3.setText("OR");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        button_login.setBackground(new java.awt.Color(255, 153, 153));
        button_login.setText("LOG IN");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        jPanel2.add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 82, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 20));

        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 230, 690));

        setSize(new java.awt.Dimension(950, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void button_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signupActionPerformed
        // TODO add your handling code here:
        if (validSignup() == true) {
            if (checkduplicate() == false) {
                insertsignupdetails();
            } else {
                JOptionPane.showMessageDialog(this, "USERNAME EXIST");
            }
        }
    }//GEN-LAST:event_button_signupActionPerformed

    private void button_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signupMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_button_signupMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        Login sign = new Login();
        sign.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_button_loginActionPerformed

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JButton button_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_agc;
    private javax.swing.JLabel label_contact;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel label_welcome;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
