/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DHAWA
 * 
 */
public class ViewRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewRecord
     */
    DefaultTableModel issuemodel;
    
    public ViewRecord() {
        initComponents();
        setdetailtotable();
    }
public void searchissue(){

    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button_all = new javax.swing.JButton();
        field_duedate = new com.toedter.calendar.JDateChooser();
        field_issuedate = new com.toedter.calendar.JDateChooser();
        button_findbook = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_issue_book_detail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View All Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 210, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 220, 5));

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -2, 17, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<- Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Issue Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Issue Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 120, 40));

        button_all.setBackground(new java.awt.Color(255, 102, 51));
        button_all.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        button_all.setText("All");
        button_all.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_allMouseClicked(evt);
            }
        });
        button_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_allActionPerformed(evt);
            }
        });
        jPanel1.add(button_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 100, 40));
        jPanel1.add(field_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 160, 30));
        jPanel1.add(field_issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 30));

        button_findbook.setBackground(new java.awt.Color(255, 102, 51));
        button_findbook.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        button_findbook.setText("Find Book");
        button_findbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_findbookMouseClicked(evt);
            }
        });
        jPanel1.add(button_findbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 260));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_issue_book_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue id", "Book Name", "Student Name", "Issue date", "Due Date", "Status", "Fine"
            }
        ));
        tbl_issue_book_detail.setGridColor(new java.awt.Color(255, 51, 51));
        tbl_issue_book_detail.setShowGrid(true);
        jScrollPane1.setViewportView(tbl_issue_book_detail);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1010, 340));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1050, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        Homepage page=new Homepage();
        page.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Homepage page=new Homepage();
        page.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        //        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void button_allMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_allMouseClicked
issuemodel.setRowCount(0);
        setdetailtotable();//searchissue();        // TODO add your handling code here:
    }//GEN-LAST:event_button_allMouseClicked

    private void button_findbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_findbookMouseClicked

        issuemodel.setRowCount(0);
        setselecteddetail();
// TODO add your handling code here:
    }//GEN-LAST:event_button_findbookMouseClicked

    private void button_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_allActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_allActionPerformed

    public void setdetailtotable(){
        
    try{
        Connection con=dbconnection.getConnection();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select id,bookname,student_name,issue_date,due_date,status,fine from issue_book_detail");
        while(rs.next()){
            int issueid=rs.getInt("id");
            String bookname=rs.getString("bookname");
            String studentname=rs.getString("Student_name");
//            int quantity=rs.getInt("issue_date");
            String issue=rs.getString("issue_date");
            String due=rs.getString("due_date");
            
            
            String status=rs.getString("status");
            int fine=rs.getInt("Fine");
            Object [] obj={issueid,bookname,studentname,issue,due,status,fine};
            issuemodel=(DefaultTableModel)tbl_issue_book_detail.getModel();
            issuemodel.addRow(obj);
        }
    }
    catch(Exception e){
        e.printStackTrace();
//       
    }
}
      public void setselecteddetail(){
//          issuemodel.setRowCount(0);
          java.util.Date date1= field_issuedate.getDate();
          java.util.Date date2= field_duedate.getDate();
          long l1=date1.getTime();
          long l2=date2.getTime();
          java.sql.Date issue_date=new java.sql.Date(l1);
          java.sql.Date due_date=new java.sql.Date(l2);
    try{
        Connection con=dbconnection.getConnection();
        PreparedStatement st=con.prepareStatement("select id,bookname,student_name,issue_date,due_date,status from issue_book_detail where issue_date between ? and ?");
       st.setDate(1,issue_date);
       st.setDate(2,due_date);
        ResultSet rs=st.executeQuery();
        while(rs.next()){
            int issueid=rs.getInt("id");
            String bookname=rs.getString("bookname");
            String studentname=rs.getString("Student_name");
//            int quantity=rs.getInt("issue_date");
            String issue=rs.getString("issue_date");
            String due=rs.getString("due_date");
            
            String status=rs.getString("status");
            Object [] obj={issueid,bookname,studentname,issue,due,status};
            issuemodel=(DefaultTableModel)tbl_issue_book_detail.getModel();
            issuemodel.addRow(obj);
        }
    }
    catch(SQLException e){
//        JOptionPane.showMessageDialog(this, due_date);
        e.printStackTrace();
//       
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_all;
    private javax.swing.JButton button_findbook;
    private com.toedter.calendar.JDateChooser field_duedate;
    private com.toedter.calendar.JDateChooser field_issuedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_issue_book_detail;
    // End of variables declaration//GEN-END:variables
}
